/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/webview/**/*.{ts,tsx,html}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--vscode-editor-background)',
        fg: 'var(--vscode-editor-foreground)',
        muted: 'var(--vscode-descriptionForeground)',
        border: 'var(--vscode-widget-border, var(--vscode-panel-border))',
        accent: 'var(--vscode-textLink-foreground)',
        'accent-hover': 'var(--vscode-textLink-activeForeground)',
        hover: 'var(--vscode-list-hoverBackground)',
        active: 'var(--vscode-list-activeSelectionBackground)',
        'btn-bg': 'var(--vscode-button-background)',
        'btn-fg': 'var(--vscode-button-foreground)',
        'btn-hover': 'var(--vscode-button-hoverBackground)',
        'btn-secondary-bg': 'var(--vscode-button-secondaryBackground)',
        'btn-secondary-fg': 'var(--vscode-button-secondaryForeground)',
        'input-bg': 'var(--vscode-input-background)',
        'input-fg': 'var(--vscode-input-foreground)',
        'input-border': 'var(--vscode-input-border, transparent)',
        badge: 'var(--vscode-badge-background)',
        'badge-fg': 'var(--vscode-badge-foreground)',
        success: 'var(--vscode-testing-iconPassed, #4ec9b0)',
        warning: 'var(--vscode-editorWarning-foreground)',
        error: 'var(--vscode-errorForeground)',
      },
      fontFamily: {
        sans: 'var(--vscode-font-family)',
        mono: 'var(--vscode-editor-font-family)',
      },
      fontSize: {
        xs: ['11px', { lineHeight: '1.5' }],
        sm: ['12px', { lineHeight: '1.55' }],
        base: ['13px', { lineHeight: '1.6' }],
        md: ['14px', { lineHeight: '1.6' }],
        lg: ['16px', { lineHeight: '1.5' }],
        xl: ['19px', { lineHeight: '1.4' }],
        '2xl': ['22px', { lineHeight: '1.35' }],
      },
      spacing: {
        0.5: '2px',
        1: '4px',
        1.5: '6px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
      },
      borderRadius: {
        none: '0',
        sm: '2px',
        DEFAULT: '4px',
        md: '6px',
        lg: '8px',
      },
      transitionDuration: {
        DEFAULT: '120ms',
      },
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.2, 0, 0, 1)',
      },
    },
  },
  plugins: [],
};
