import * as vscode from 'vscode';
import type { WebviewStringsDTO } from '../../shared/strings';

export function buildWebviewStrings(): WebviewStringsDTO {
  return {
    refresh: vscode.l10n.t('Refresh'),
    loadingDiscussions: vscode.l10n.t('Loading discussions…'),
    loadingDiscussion: vscode.l10n.t('Loading discussion…'),
    noDiscussions: vscode.l10n.t('No discussions yet.'),
    noRepoDetected: vscode.l10n.t('No GitHub repository detected'),
    noRepoHint: vscode.l10n.t(
      'Open a folder with a GitHub remote, or set agora.repository in Settings.',
    ),
    failedToLoad: vscode.l10n.t('Failed to load discussions'),
    back: vscode.l10n.t('Back'),
    openInBrowser: vscode.l10n.t('Open in browser'),
    markedAsAnswer: vscode.l10n.t('Marked as answer'),
    answer: vscode.l10n.t('Answer'),
    locked: vscode.l10n.t('Locked'),
    closed: vscode.l10n.t('Closed'),
    answered: vscode.l10n.t('Answered'),
    categories: vscode.l10n.t('Categories'),
    all: vscode.l10n.t('All'),
    commentSingular: vscode.l10n.t('comment'),
    commentPlural: vscode.l10n.t('comments'),
    discussionSingular: vscode.l10n.t('discussion'),
    discussionPlural: vscode.l10n.t('discussions'),
    cancel: vscode.l10n.t('Cancel'),
    edit: vscode.l10n.t('Edit'),
    delete: vscode.l10n.t('Delete'),
    save: vscode.l10n.t('Save'),
    reply: vscode.l10n.t('Reply'),
    newDiscussion: vscode.l10n.t('New discussion'),
    composerPlaceholder: vscode.l10n.t('Write a comment in Markdown…'),
    composerSubmit: vscode.l10n.t('Comment'),
    composerPreview: vscode.l10n.t('Preview'),
    composerEdit: vscode.l10n.t('Edit'),
    composerShortcutHint: vscode.l10n.t('⌘/Ctrl + Enter to submit · ⌘B / ⌘I / ⌘K · supports Markdown'),
    composerNothingToPreview: vscode.l10n.t('Nothing to preview.'),
    composerCategoryLabel: vscode.l10n.t('Category'),
    composerTitleLabel: vscode.l10n.t('Title'),
    composerTitlePlaceholder: vscode.l10n.t('A short, descriptive title'),
    composerBodyLabel: vscode.l10n.t('Body'),
    markAsAnswer: vscode.l10n.t('Mark as answer'),
    unmarkAsAnswer: vscode.l10n.t('Unmark as answer'),
    lockDiscussion: vscode.l10n.t('Lock discussion'),
    unlockDiscussion: vscode.l10n.t('Unlock discussion'),
    deleteConfirm: vscode.l10n.t('Delete this comment? This cannot be undone.'),
    deleteDiscussionConfirm: vscode.l10n.t('Delete this discussion and all its comments? This cannot be undone.'),
    addReaction: vscode.l10n.t('Add reaction'),
    repliesClosedNotice: vscode.l10n.t(
      'This discussion is locked — replies are closed.',
    ),
  };
}
